#!/usr/bin/env bash

test -z $1 && echo 'No device' && exit 1
test ! -c "/dev/video$1" && echo "Can not open /dev/video$1" && exit 1

today=$(date '+%Y-%m-%d')

mkdir -p out/$today
rm out/$today/*

ffmpeg -i "/dev/video$1" \
-nostdin \
-s 728x410 \
-f hls \
-hls_time 4 \
-hls_list_size 4 \
-hls_base_url "/stream/$today/" \
-hls_playlist_type event \
-strftime 1 \
-use_localtime 1 \
-hls_flags delete_segments+round_durations+omit_endlist+append_list \
-hls_segment_filename  "out/$today/segment_%Y-%m-%d_%s.ts" \
 out/$today/index.m3u8 > out/$today/stream.log &> /dev/null & disown 
